version: '3.8'
services:
  custom_openresty:
    image:  openresty/openresty:1.19.9.1-2-bionic
    hostname: openrestyserver
    ports:
    - 8080:8080
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf